# this corresponds to the default config
train:
  dataset_path: Sentinel2:split=TRAIN:root=/NAS6/Members/linchenxi/projects/RS_foundation_model/satlas
  batch_size_per_gpu: 24
  num_workers: 5
  multimodal: false
student:
  arch: vit_large
  block_chunks: 4
  num_register_tokens: 2
  in_chans: 9
crops:
  global_crops_size: 368
  local_crops_size: 192
ibot:
  mask_sample_probability: 0.3
  mask_ratio_min_max:
  - 0.1
  - 0.3