# this corresponds to the default config
train:
  dataset_path: ImageNet:split=TRAIN:root=/NAS6/Members/linchenxi/ILSVRC:extra=/NAS6/Members/linchenxi/ILSVRC
  batch_size_per_gpu: 64
student:
  block_chunks: 4
