# this corresponds to the default config
train:
  dataset_path: Multimodality:split=TRAIN:root=/NAS3/Members/linchenxi/projects/foundation_model/sen12ms
  batch_size_per_gpu: 64
  num_workers: 5
  multimodal: true
student:
  arch: vit_base
  arch_s1: vit_base
  arch_s2: vit_base
  block_chunks: 4
  num_register_tokens: 2
  in_chans_s1: 2
  in_chans_s2: 13
crops:
  global_crops_size: 192
  local_crops_size: 96
ibot:
  mask_sample_probability: 0.3
  mask_ratio_min_max:
  - 0.1
  - 0.3